# -*- coding: utf-8 -*-
"""SMART100_PSA_Analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_pJEKpvjyoTmG0v1W6WIS-6WiBo--Cep

# SMART100 PSA Analyzer

## 사용 순서
1. **셀 1** 실행 → 공통 코드 로드 (BaseAnalyzer)
2. **셀 2** 실행 → LOFW 코드 로드
3. **셀 3** 실행 → SBLOCA 코드 로드
4. **셀 4 또는 5** 실행 → 원하는 사고 유형 분석

> 셀 1~3은 항상 실행해야 함 (공통 + 사고별 클래스 로드)
> 분석은 셀 4(LOFW) 또는 셀 5(SBLOCA) 중 하나만 실행
"""

# ============================================================
# 셀 1: 공통 코드 (BaseAnalyzer) - 항상 실행
# ============================================================

import pandas as pd
import numpy as np
from pathlib import Path
from google.colab import files
import io


class BaseAnalyzer:
    """
    공통 베이스 클래스
    - PCT 계산, RCP 상태, 결과 저장 등 모든 사고 유형에서 동일한 로직
    - _detect_rt(), _check_prhrs_count()는 사고별로 다르므로 비워둠
      → 각 사고 analyzer(LOFWAnalyzer, SBLOCAAnalyzer)에서 구현
    """

    ACCIDENT_TYPE = 'Unknown'
    CD_THRESHOLD  = 670  # PCT Core Damage 판정 기준 (K)

    def __init__(self):
        self.var_mapping_df = None
        self.scenarios_data = []
        print('=' * 70)
        print(f'📊 SMART100 {self.ACCIDENT_TYPE} Analyzer')
        print('=' * 70)
        print('\n사용 순서:')
        print('  1. analyzer.step1_load_mapping()       → 변수 매핑 파일 업로드')
        print('  2. analyzer.step2_upload_files()       → 시나리오 파일들 업로드')
        print('  3. analyzer.show_results()             → 결과 확인')
        print('  4. analyzer.save_results("결과.csv")   → CSV 저장')
        print('=' * 70)

    def step1_load_mapping(self):
        print(f'\n{"="*70}')
        print('Step 1: 변수 매핑 파일 업로드')
        print(f'{"="*70}')
        print('📂 smart100데이터_변수명_확인.xlsx 파일을 선택하세요.\n')
        uploaded = files.upload()
        if not uploaded:
            print('❌ 파일이 업로드되지 않았습니다.')
            return
        filename = list(uploaded.keys())[0]
        self.var_mapping_df = pd.read_excel(io.BytesIO(uploaded[filename]))
        print(f'✓ 변수 매핑 로드: {filename} ({len(self.var_mapping_df)}개 변수)')
        print('\n▶ 다음: analyzer.step2_upload_files()')

    def step2_upload_files(self):
        if self.var_mapping_df is None:
            print('❌ 먼저 step1_load_mapping()을 실행하세요!')
            return
        print(f'\n{"="*70}')
        print(f'Step 2: {self.ACCIDENT_TYPE} 시나리오 파일 업로드')
        print(f'{"="*70}')
        print('📂 시나리오 파일들을 선택하세요 (여러 개 선택 가능)\n')
        uploaded = files.upload()
        if not uploaded:
            print('❌ 파일이 업로드되지 않았습니다.')
            return
        print(f'\n✓ {len(uploaded)}개 파일 업로드 완료')
        print('-' * 70)
        for filename, content in uploaded.items():
            print(f'📊 {filename}...', end=' ')
            try:
                df_raw = pd.read_excel(io.BytesIO(content))
                df_raw = df_raw.dropna(subset=['time'])
                df = df_raw.iloc[2:].copy()
                df['time'] = pd.to_numeric(df['time'])
                for c in df.columns:
                    df[c] = pd.to_numeric(df[c], errors='coerce')
                result = self._analyze_single(filename, df)
                self.scenarios_data.append(result)
                self._print_result(result)
            except Exception as e:
                print(f'✗ 오류: {e}')
        print(f'\n{"="*70}')
        print(f'✓ 분석 완료: {len(self.scenarios_data)}개 시나리오')
        print('\n▶ 다음: analyzer.show_results()')

    def _analyze_single(self, filename, df):
        scenario_name = Path(filename).stem
        rt_time       = self._detect_rt(df)
        reactor_trip  = 'Success' if rt_time < df['time'].max() * 0.99 else 'Fail'
        rcp_status    = self._check_rcp_status(df, rt_time)
        prhrs_count   = self._check_prhrs_count(df, rt_time)
        pct_max, pct_time = self._calculate_pct(df, rt_time)
        outcome       = 'CD' if pct_max >= self.CD_THRESHOLD else 'OK'
        return {
            'Scenario':     scenario_name,
            'Reactor_Trip': reactor_trip,
            'RCP_Status':   rcp_status,
            'PRHRS_count':  prhrs_count,
            'PCT_max':      pct_max,
            'PCT_time':     pct_time,
            'Outcome':      outcome,
        }

    def _print_result(self, result):
        print(f'✓ PRHRS={result["PRHRS_count"]}계통, '
              f'PCT={result["PCT_max"]:.1f}K @ {result["PCT_time"]:.0f}s, '
              f'{result["Outcome"]}')

    def _check_rcp_status(self, df, rt_time):
        df_after = df[(df['time'] > rt_time) & (df['time'] < rt_time + 200)]
        if len(df_after) == 0:
            return 'Unknown'
        avg_head = df_after[['pmphead','pmphead.1','pmphead.2','pmphead.3']].mean().mean()
        if avg_head > 1000:
            return 'Running'
        elif avg_head > -200:
            return 'Coast-down'
        else:
            return 'Natural Circulation'

    def _calculate_pct(self, df, rt_time):
        """
        PCT 계산 - RT 이후 구간에서 3개 노드 중 최대값
        httemp   = 120000803 (8번 노드)
        httemp.1 = 120000903 (9번 노드)
        httemp.2 = 120001003 (10번 노드)
        """
        pct_cols = ['httemp', 'httemp.1', 'httemp.2']
        df_valid = df[df['time'] >= rt_time].copy()
        df_valid = df_valid[(df_valid[pct_cols] < 10000).all(axis=1)]
        if len(df_valid) == 0:
            return 0.0, 0.0
        df_valid['pct_row_max'] = df_valid[pct_cols].max(axis=1)
        pct_max  = df_valid['pct_row_max'].max()
        pct_time = df_valid.loc[df_valid['pct_row_max'].idxmax(), 'time']
        return float(pct_max), float(pct_time)

    # 사고별로 반드시 구현해야 하는 함수
    def _detect_rt(self, df):
        raise NotImplementedError(f'{self.__class__.__name__}에서 _detect_rt()를 구현하세요.')

    def _check_prhrs_count(self, df, rt_time):
        raise NotImplementedError(f'{self.__class__.__name__}에서 _check_prhrs_count()를 구현하세요.')

    def show_results(self):
        if not self.scenarios_data:
            print('❌ 분석된 시나리오가 없습니다.')
            return None
        df = pd.DataFrame(self.scenarios_data)
        print(f'\n{"="*70}')
        print(f'{self.ACCIDENT_TYPE} 분석 결과 요약')
        print(f'{"="*70}')
        print(f'총 시나리오:      {len(df)}개')
        print(f'OK:              {(df["Outcome"]=="OK").sum()}개')
        print(f'Core Damage(CD): {(df["Outcome"]=="CD").sum()}개')
        print(f'평균 PCT:         {df["PCT_max"].mean():.1f} K')
        print(f'최고 PCT:         {df["PCT_max"].max():.1f} K')
        print(f'\nPRHRS 계통수 분포:')
        print(df['PRHRS_count'].value_counts().sort_index().to_string())
        print(f'{"="*70}')
        return df

    def save_results(self, filename=None):
        if not self.scenarios_data:
            print('❌ 저장할 데이터가 없습니다.')
            return
        if filename is None:
            filename = f'{self.ACCIDENT_TYPE.lower()}_results.csv'
        df = pd.DataFrame(self.scenarios_data)
        df.to_csv(filename, index=False, encoding='utf-8-sig')
        print(f'✓ 저장: {filename}')
        files.download(filename)

print('✓ 셀 1 완료: BaseAnalyzer 로드됨')

# ============================================================
# 셀 2: LOFW 코드 - 항상 실행
# ============================================================

class LOFWAnalyzer(BaseAnalyzer):
    """
    LOFW 전용 Analyzer
    BaseAnalyzer와 다른 부분:
      - _detect_rt()         : LOFW는 RT가 초기에 발생 → 50초 고정
      - _check_prhrs_count() : feedwater 유량 기준 (mflowj.13~16, 임계값 0.5 kg/s)
    """

    ACCIDENT_TYPE = 'LOFW'

    def _detect_rt(self, df):
        # LOFW는 RT가 사고 초기에 발생 → PCT 계산 시작점 50초 고정
        return 50.0

    def _check_prhrs_count(self, df, rt_time):
        """
        mflowj.13~16 = feedwater #1~4 flow (307000000~367000000)
        임계값: 0.5 kg/s 이상 = 작동
        """
        try:
            df_after = df[df['time'] > rt_time + 50]
            if len(df_after) == 0:
                return 0
            fw_cols = ['mflowj.13', 'mflowj.14', 'mflowj.15', 'mflowj.16']
            avg_flow = df_after[fw_cols].mean()
            return int((avg_flow > 0.5).sum())
        except:
            return -1

print('✓ 셀 2 완료: LOFWAnalyzer 로드됨')

# ============================================================
# 셀 3: SBLOCA 코드 - 항상 실행
# ============================================================

class SBLOCAAnalyzer(BaseAnalyzer):
    """
    SBLOCA 전용 Analyzer
    BaseAnalyzer와 다른 부분:
      - _detect_rt()         : 초기 출력 5% 이하 시점 자동 감지
      - _check_prhrs_count() : HX 열출력 기준 (cntrlvar.25~28, 임계값 10000 W)
      - _analyze_single()    : RT_time 컬럼 추가
    """

    ACCIDENT_TYPE = 'SBLOCA'

    def _detect_rt(self, df):
        # 초기 출력의 5% 이하로 떨어지는 첫 시점 = RT 시점
        initial_power = df.iloc[0]['rktpow']
        threshold = initial_power * 0.05
        trip_rows = df[df['rktpow'] < threshold]
        return float(trip_rows['time'].min()) if len(trip_rows) > 0 else float(df['time'].max())

    def _check_prhrs_count(self, df, rt_time):
        """
        cntrlvar.25~28 = PRHRS HX #1~4 열출력 (W)
        SBLOCA에서는 feedwater 유량이 파단 영향으로 부정확 → HX 열출력 사용
        임계값: 10000 W 이상 = 작동
        """
        try:
            df_after = df[df['time'] > rt_time + 100]
            if len(df_after) == 0:
                return 0
            hx_cols = ['cntrlvar.25', 'cntrlvar.26', 'cntrlvar.27', 'cntrlvar.28']
            avg_heat = df_after[hx_cols].mean()
            return int((avg_heat > 10000).sum())
        except:
            return -1

    def _analyze_single(self, filename, df):
        # 공통 분석 실행 후 RT_time 컬럼 추가
        result = super()._analyze_single(filename, df)
        result['RT_time'] = self._detect_rt(df)
        return result

    def _print_result(self, result):
        print(f'✓ RT={result["RT_time"]:.0f}s, PRHRS={result["PRHRS_count"]}계통, '
              f'PCT={result["PCT_max"]:.1f}K @ {result["PCT_time"]:.0f}s, '
              f'{result["Outcome"]}')

    def show_results(self):
        df = super().show_results()
        if df is not None and 'RT_time' in df.columns:
            print(f'\nRT 시간 분포 (s):')
            print(df['RT_time'].describe().to_string())
        return df

print('✓ 셀 3 완료: SBLOCAAnalyzer 로드됨')
print('\n✅ 모든 클래스 로드 완료. 아래 셀에서 분석을 시작하세요.')

# ============================================================
# 셀 4: LOFW 분석 실행
# ============================================================

analyzer = LOFWAnalyzer()
analyzer.step1_load_mapping()
analyzer.step2_upload_files()
df_lofw = analyzer.show_results()
display(df_lofw)
analyzer.save_results('lofw_results.csv')

# ============================================================
# 셀 5: SBLOCA 분석 실행
# ============================================================

analyzer = SBLOCAAnalyzer()
analyzer.step1_load_mapping()
analyzer.step2_upload_files()
df_sbloca = analyzer.show_results()
display(df_sbloca)
analyzer.save_results('sbloca_results.csv')